# name: ci

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Use Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: 18
#         cache: 'npm'
#     - run: npm ci
#     - run: npx playwright install
#     - run: npm test
  
#     - uses: actions/upload-artifact@master
#       with:
#         name: allure-results
#         path: allure-results
#         # retention-days: 20
        
#     - name: Get Allure history
#       uses: actions/checkout@v4
#       if: always()
#       continue-on-error: true
#       with:
#         ref: gh-pages
#         path: gh-pages
    
#     - name: Test marketplace action
#       uses: simple-elf/allure-report-action@master
#       if: always()
#       id: allure-report
#       with:
#         allure_results: allure-results
#         gh_pages: gh-pages
#         allure_report: allure-report
#         allure_history: allure-history
#         keep_reports: 20

#     - name: Deploy report to Github Pages
#       if: always()
#       uses: peaceiris/actions-gh-pages
#       env:
#         PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         PUBLISH_BRANCH: gh-pages
#         PUBLISH_DIR: allure-history

name: Playwright Tests
on:
  push:
    branches:  main
  pull_request:
    branches:  main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest
    - uses: actions/setup-node@latest
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests on chromium only
      run: npx playwright test --project=chromium
    - name: Get Allure history
      uses: actions/checkout@latest
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@latest
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history   

        # - name: Upload Allure report artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: allure-report
    #     path: allure-results
    # - name: Generate Allure report
    #   uses: simple-elf/allure-report-action@master
    #   id: allure-report
    #   with:
    #     allure_results: allure-results
    #     gh_pages: gh-pages
    #     allure_report: allure-report
    #     allure_history: allure-history

    # - name: Deploy report to Gihub Pages
    #   if: always()
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     PUBLISH_BRANCH: main  # Update with your branch name
    #     PUBLISH_DIR: allure-history.json
  
    # # - name: Deploy report to Gihub Pages
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
    #   if: always()
    #   uses: peaceiris/actions-gh-pages
    #   with:
    #     PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     PUBLISH_BRANCH: main  # Update with your branch name
    #     PUBLISH_DIR: allure-history.json
